name: Issue Opened

on:
  issues:
    types: [opened]

jobs:
  compile:
    name: Assignee
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/assign-issue
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
